### ISSUE TITLE
Crashed while entering minecells dimension or go back to overwold (Sinytra connector)

### ISSUE THREAD

**Issue by liangmoe** [null2264/LibreExpFix#6] opened 2024-01-18 12:29 UTC
crashreport: https://mclo.gs/6ZtZlV1

[Mine cells](https://modrinth.com/mod/minecells), [Sinytra Connector](https://modrinth.com/mod/connector)

**Comment by null2264** [comment] 2024-01-19 00:12
Duplicate of GH-5

Forge doesn't play well with cross-version mods apparently, I'll figure something out later today.

**Closed as not planned by null2264** 2024-01-19 00:12 UTC
